language: node_js
node_js:
  - 4.1
before_script:
  - npm install -g grunt-cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then npm test ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Q6arynFz6IQhdtOHJAaRTBjkceAAdpoYVyp2IcydO8PS0oTfc5IphR6Mbr5EKzU6Y8V0NBLTLHtpDLBqCThNR7G0uavWQcQ2LzUswUMCCKAE84LFU/sfmTNDnAdm/ialGnoomPg6KgpFt/ZSwT8prb9g4GXFPVQq8Oo9VJcF7WU="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "namankanakiya/connect-azuretables"
      description: "Connect sessions store based on Azure Table Storage"
    notification_email: naman.kanakiya@gmail.com
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search lib"
    branch_pattern: coverity_scan